apiVersion: v1
kind: Namespace
metadata:
  name: dfgfghg-staging
  labels:
    environment-id: env_c5e709ce-6b26-48ef-b2e2-3cdee5bb13bd
    project-id: project_0212766b-1b0b-464c-b212-379a59ef4fd4
    project-name: dfgfghg
    environment-name: staging
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
